--- #YAML:1.0
name:               Mail-SpamAssassin
version:            3.003002
abstract:           SpamAssassin is an extensible email filter which is used to identify spam
author:
    - The Apache SpamAssassin Project <dev@spamassassin.apache.org>
license:            apache
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Archive::Tar:   1.23
    Digest::SHA1:   0
    Errno:          0
    File::Copy:     2.02
    File::Spec:     0.8
    HTML::Parser:   3.43
    Mail::DKIM:     0.31
    Net::DNS:       0.34
    NetAddr::IP:    4.000
    Pod::Usage:     1.1
    Sys::Hostname:  0
    Time::HiRes:    0
    Time::Local:    0
resources:
    bugtracker:   https://issues.apache.org/SpamAssassin/
    homepage:     http://spamassassin.apache.com/
    license:      http://www.apache.org/licenses/LICENSE-2.0.html
    MailingList:  http://wiki.apache.org/spamassassin/MailingLists
    repository:   http://svn.apache.org/repos/asf/spamassassin/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    Archive::Tar:         1.23
    Compress::Zlib:       0
    DB_File:              0
    DBI:                  0
    Encode::Detect:       0
    Getopt::Long:         2.32
    HTTP::Date:           0
    IO::Socket::INET6:    0
    IO::Socket::SSL:      0
    IO::Zlib:             1.04
    IP::Country::Fast:    0
    LWP::UserAgent:       0
    Mail::DKIM:           0.37
    Mail::SPF:            0
    MIME::Base64:         0
    Net::Ident:           0
    Net::SMTP:            0
    Razor2::Client::Agent:  2.61
