DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=
	sa-test.spamassassin.org; h=from:to:subject:message-id:date
	:mime-version:content-type; s=t0768; bh=15pFrAvOGi+eHKJgB6psh6iI
	BCbvYSuhPj+wQn6C7Ss=; b=iWP4EFdIfxFV+LOvwL7bLA5qIzHOcmvZXCJbmb1X
	8SAAhZHz6FJ7TTP6EfSbg2jtHZfrZSsHo5III1BTD2DMC0d/wMjNS+LJh8E1akU4
	jRc1yNNpKJ7FyUaydvimvOmg
From: SpamAssassin Test <test@sa-test.spamassassin.org>
To: undisclosed-recipients:;
Subject: test message 17
Message-ID: <4A294538.10002@spamassassin.org>
Date: Mon, 08 Jun 2009 12:00:00 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii

testing
