DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=
	sa-test.spamassassin.org; h=from:to:subject:message-id:date
	:mime-version:content-type; s=t2048a; bh=15pFrAvOGi+eHKJgB6psh6i
	IBCbvYSuhPj+wQn6C7Ss=; b=R5ridJNpcMCrKMc2FOG3ze+4GwrMK5IvICIN4kx
	PvrbRuMTJFp4Tj93rfm71eVXrc7S1ZFXdSV3S4Nyaz4eHWraNmnzSXwjKloXDk6B
	sk+3gO0KaaoJwYtctbgCUXcx/9v9QWwLwFoEhk67BigvqjPXDOLMDg4ei9q1dpgR
	FHzKs149Q8PzMWqYD0Um+0mNe+Mu/43Ze+HkQt7lkXD9iBhs1c5slj0Nmn+0sSyW
	ewRtyYDxLc5N72M9LLAQ8x7zpLBhKURpX0+aowNUSOA9Zkz3YwmJIx5a9qVPhDkK
	yuDXmRvvx2cP+2BnpaEUMGV9ftZ3Qrg/bqSI63u7eFVGwIw==
From: SpamAssassin Test <test@sa-test.spamassassin.org>
To: undisclosed-recipients:;
Subject: test message 15
Message-ID: <4A294538.10002@spamassassin.org>
Date: Mon, 08 Jun 2009 12:00:00 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii

testing
