DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=
	sa-test.spamassassin.org; h=from:to:subject:message-id:date
	:mime-version:content-type; s=t1024c; bh=15pFrAvOGi+eHKJgB6psh6i
	IBCbvYSuhPj+wQn6C7Ss=; b=VlSVJyxKuRBvcrM/jfJvCoio0KQsm7qe+elakmn
	QGGFQDdWZh682GdBlRIqfHL6gCdEe0cjpSvZoHXlQGyRaHN9a63bU9DFtzSGTj3D
	lXrEI1UA71GV2PJjVqLO5CIzsUCrmVYuzX0eoUGtDmyPS7VPRGZjMNGwIaTgukVw
	igso=
From: SpamAssassin Test <test@sa-test.spamassassin.org>
To: undisclosed-recipients:;
Subject: test message 11
Message-ID: <4A294538.10002@spamassassin.org>
Date: Mon, 08 Jun 2009 12:00:00 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii

testing
