DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=
	sa-test.spamassassin.org; h=from:to:subject:message-id:date
	:mime-version:content-type; s=t0768; bh=15pFrAvOGi+eHKJgB6psh6iI
	BCbvYSuhPj+wQn6C7Ss=; b=YtY1X9FaRsHzUvYU8X/XG1NI+tmKmx1d/uzkrnAF
	qry2NWv+8FI3HCvXXRa9g8bmqPI+hbxUKv7MiQHkihrKIYr/kA9DIYyZEVOBO/Um
	jqemqkPx6GRmsqmB9GyBnOiU
From: SpamAssassin Test <test@sa-test.spamassassin.org>
To: undisclosed-recipients:;
Subject: test message 3
Message-ID: <4A294538.10002@spamassassin.org>
Date: Mon, 08 Jun 2009 12:00:00 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii

testing
