DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=
	sa-test.spamassassin.org; h=from:to:subject:message-id:date
	:mime-version:content-type; s=t1024b; bh=15pFrAvOGi+eHKJgB6psh6i
	IBCbvYSuhPj+wQn6C7Ss=; b=V84iCIHoIcDF0WJmh0Xq7BcUPqO56b6+TkJw4nr
	nk1wt0bwXnJldd8o9sf/EB84Dwle1URsnoBOi83b+lVe8K0uIJbQcfGUIpE4J57Z
	YWj978mJImZuClTJnDcoAdHBeG2OHT/KCw2XmpDOBUr1CXAySqJweetbakqxQxNj
	0vuk=
From: SpamAssassin Test <test@sa-test.spamassassin.org>
To: undisclosed-recipients:;
Subject: test message 10
Message-ID: <4A294538.10002@spamassassin.org>
Date: Mon, 08 Jun 2009 12:00:00 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii

testing
