DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=
	sa-test.spamassassin.org; h=from:to:subject:message-id:date
	:mime-version:content-type; s=t2048b; bh=15pFrAvOGi+eHKJgB6psh6i
	IBCbvYSuhPj+wQn6C7Ss=; b=pxVnohrPidydig1tDpB5IsIejSsxzbrpqSyOQh0
	jfNwfzlUli098twNZPue+IqOosGV1HJtFHU5TOZyfB9P9nPbBnWmCHI2EKTp3uaV
	Iy/xeTbf20x17ZvwGqOITz81yUESB+4rFHFaAaL4lBf/9BHd7fU/kZbsX1sefp22
	TH4Zzm3f+q9Mx7zbg0vMfWRe8iZ5rA0rbj3FIX/i6oSmXtSIkV/9XHRJnG1fwsLS
	V9mltYNc/GN27ODQCJ9QBFBHZnGgONBd/QXXCJWTXMR2N6zi9ex36MQMF+R0u7q5
	0S+zFiR5MsX8upEIFOIP0JU+WS/2eaG8drhTHm3SkyQT6xQ==
From: SpamAssassin Test <test@sa-test.spamassassin.org>
To: undisclosed-recipients:;
Subject: test message 16
Message-ID: <4A294538.10002@spamassassin.org>
Date: Mon, 08 Jun 2009 12:00:00 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii

testing
