DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=
	sa-test.spamassassin.org; h=from:to:subject:message-id:date
	:mime-version:content-type; s=t1280; bh=15pFrAvOGi+eHKJgB6psh6iI
	BCbvYSuhPj+wQn6C7Ss=; b=f2vBvTkR2Fazg5I1pBae55DyY2y7GTGgiUpd5+Rk
	Yl6Y2rTOiiBhE7EiffuxHPYWS8LEi37JDW0q5RTKJrEe2cNqAuIxerXigXMqMvs5
	PNk/jyN9tkcq2STEAfwAzp71VDHkGcTd7V729MBTMmC7hJ/3TE7vYjtevmo1uYUP
	jTJeDD5baDximaxnyE64ckJ43kEC4nUo1rkZ/aFPt5tUKQ==
From: SpamAssassin Test <test@sa-test.spamassassin.org>
To: undisclosed-recipients:;
Subject: test message 13
Message-ID: <4A294538.10002@spamassassin.org>
Date: Mon, 08 Jun 2009 12:00:00 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii

testing
