From: SpamAssassin Test <test@sa-test.spamassassin.org>
To: undisclosed-recipients:;
Subject: test message 7
Message-ID: <4A294538.10002@spamassassin.org>
Date: Mon, 08 Jun 2009 12:00:00 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=
	sa-test.spamassassin.org; h=from:to:subject:message-id:date
	:mime-version:content-type; s=t0768; t=1244419200; bh=15pFrAvOGi
	+eHKJgB6psh6iIBCbvYSuhPj+wQn6C7Ss=; b=r77n22svRRIvdSz7r7+4voona+
	QvX0Rlb5aPXS4P0pyHgYz/w/PklSfqhAdZbfUkhYfdQ3UcczfsdoDBjkhTQ8c8bK
	3qo0rBY5yoKp+Nb9qxIwHkkPpUfoAfEC02SBgo

testing
