--- #YAML:1.0
# http://module-build.sourceforge.net/META-spec.html
# http://module-build.sourceforge.net/META-spec-blead.html
#
name:     Mail-SpamAssassin
version:  3.003000
version_from: lib/Mail/SpamAssassin.pm
abstract: SpamAssassin is an extensible email filter which is used to identify spam
license: apache

requires:
    Digest::SHA1:                   0
    Errno:                          0
    File::Copy:                     2.02
    File::Spec:                     0.8
    HTML::Parser:                   3.43
    Net::DNS:                       0.34
    NetAddr::IP:                    0
    Pod::Usage:                     1.1
    Sys::Hostname:                  0
    Time::HiRes:                    0
    Time::Local:                    0

recommends:
    MIME::Base64:                   0
    DB_File:                        0
    Net::SMTP:                      0
    Mail::SPF:                      0
    IP::Country::Fast:              0
    Razor2::Client::Agent:          2.61
    Net::Ident:                     0
    IO::Socket::INET6:              0
    IO::Socket::SSL:                0
    Compress::Zlib:                 0
    Mail::DKIM:                     0.28
    DBI:                            0
    Getopt::Long:                   2.32
    LWP::UserAgent:                 0
    HTTP::Date:                     0
    Archive::Tar:                   1.23
    IO::Zlib:                       1.04
    Encode::Detect:                 0

installdirs:  site
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
author:
    - The Apache SpamAssassin Project <dev at spamassassin.apache.org>

resources:
  homepage: http://SpamAssassin.apache.org/
  bugtracker: http://issues.apache.org/SpamAssassin/

meta-spec:
  url:     http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2


