#!/bin/sh

SCORESET="1"
NAME="set$SCORESET"

if [ ! -f "ORIG/ham-$NAME.log" -o ! -f "ORIG/spam-$NAME.log" ]; then
	echo "Couldn't find logs for $NAME" >&2
	exit 1
fi

if [ "x$1" = "x" ]; then
echo "[Doing a scoreset $SCORESET score-generation run]"

# Clean out old runs
echo "[Cleaning up]"
rm -rf spam-validate.log nonspam-validate.log ham-validate.log spam.log nonspam.log ham.log NSBASE SPBASE tmp make.output freqs perceptron.scores \
	gen-$NAME.out gen-$NAME.scores gen-$NAME.validate
make clean >/dev/null

# Generate 90/10 split logs
echo "[Generating 90/10 split ham]"
mkdir NSBASE SPBASE
cd NSBASE
../tenpass/split-log-into-buckets 10 < ../ORIG/ham-$NAME.log > /dev/null
cat split-[1-9].log > nonspam.log
rm -f split-[1-9].log
mv split-10.log nonspam-validate.log

echo "[Generating 90/10 split spam]"
cd ../SPBASE
../tenpass/split-log-into-buckets 10 < ../ORIG/spam-$NAME.log > /dev/null
cat split-[1-9].log > spam.log
rm -f split-[1-9].log
mv split-10.log spam-validate.log
cd ..

echo "[Setting up for gen run]"
# Ok, setup for a run
ln -s SPBASE/spam.log .
ln -s NSBASE/nonspam.log .
ln -s NSBASE/nonspam.log ham.log
ln -s SPBASE/spam-validate.log .
ln -s NSBASE/nonspam-validate.log .
ln -s NSBASE/nonspam-validate.log ham-validate.log

# try to find number of processors
numcpus=`cpucount 2>/dev/null || egrep -c '^processor\b' /proc/cpuinfo 2>/dev/null || echo 1`

echo "[Generating perceptron]"
# Generate perceptron with full logs
make -j $numcpus SCORESET=$SCORESET > make.output 2>&1

( echo "[gen run start]" ; pwd ; date ; \
./perceptron -p 2.0 -e 100; \
mv perceptron.scores gen-$NAME.scores ; \
echo "[gen run end]" ; pwd ; date ) | tee gen-$NAME.out

else

# This needs to have 50_scores.cf in place first ...
echo "[gen validation results]"
./logs-to-c --spam=SPBASE/spam-validate.log \
	--nonspam=NSBASE/nonspam-validate.log \
	--count --cffile=../rules --scoreset=$SCORESET | tee gen-$NAME.validate

echo "[STATISTICS file generation]"
./mk-baseline-results $SCORESET | tee gen-$NAME.statistics
fi

exit 0
