#!/bin/bash

echo "

NOTE: this is a sample.  You need to customise it to
fit your corpus of spam and nonspam mails.

"
cd /home/jm/ftp/spamassassin/masses

set -x
date

mv spam.local nonspam.local logs/old

./mass-check /local2/mail-archives/kelsey.spamtrap.gz >> spam.local
./mass-check /local2/mail-archives/spam.2000-2001.gz >> spam.local

./mass-check /local2/mail-archives/scoop.1999.gz >> nonspam.local
./mass-check /local2/mail-archives/oldmail.1998.gz >> nonspam.local

./mass-check-for-jm ; sh commands.sh

for f in /local2/mail-archives/crackmice-old/* ; do
  ./mass-check $f >> nonspam.local
done
# the new stuff is run on dogma now

dog=dogma.slashnull.org
rsync -vrze ssh $dog:ftp/spamassassin/masses/spam.log spam.dogma
rsync -vrze ssh $dog:ftp/spamassassin/masses/nonspam.log nonspam.dogma

cat nonspam.local nonspam.dogma logs/contrib/nonspam.log* > nonspam.log
cat spam.local spam.dogma logs/contrib/spam.log* > spam.log

./hit-frequencies > freqs
./mk-baseline-results

./copy-logs-to-deimos

make clean
make evolve
date
./continual_evolve.sh -s 100 -b 20.0 -c 1.001


