#!/bin/bash

echo "

NOTE: this is a sample.  You need to customise it to
fit your corpus of spam and nonspam mails.

"
cd /home/jm/ftp/spamassassin/masses

set -x
date

mv spam.log nonspam.log logs/old

cat logs/contrib/nonspam.log* > nonspam.log
cat logs/contrib/spam.log* > spam.log

# ./download-trapped-spam
# ./mass-check /local2/mail-archives/spamtrap/mbox >> spam.log

./mass-check /local2/mail-archives/kelsey.spamtrap.gz >> spam.log
./mass-check /local2/mail-archives/spam.2000-2001.gz >> spam.log

./mass-check /local2/mail-archives/scoop.1999 >> nonspam.log
./mass-check /local2/mail-archives/oldmail.1998 >> nonspam.log

./mass-check-for-jm ; sh commands.sh

for f in /local2/mail-archives/crackmice-old/* ; do
  ./mass-check $f >> nonspam.log
done

rsync -vrze ssh dogma.slashnull.org:ftp/spamassassin/masses/spam.log spam.dogma
cat spam.dogma >> spam.log
rsync -vrze ssh dogma.slashnull.org:ftp/spamassassin/masses/nonspam.log nonspam.dogma
cat nonspam.dogma >> nonspam.log

./mk-baseline-results
./hit-frequencies > freqs

make clean
make
date
./continual_evolve.sh -s 100 -b 10.0 -c 1.001


