#!/bin/sh

# Cron script for "release".  see "backend/nitemc/crontab.txt"

TZ=UTC; export TZ
DIR=$HOME/versions/trunk
#Changed for spamassassin-vm
SVN=/usr/bin/svn
SVNVERS=/usr/bin//svnversion

if [ ! -d $DIR ]; then
  echo "Whaaaa?!?  No directory?" >&2
  exit 2
fi

cd $DIR
$SVN update > /dev/null
if [ $? -ne 0 ]; then
  echo "Problem doing svn update" >&2
  exit 1
fi

RREV=`$SVNVERS .`
REV=`echo $RREV | awk -F: '{print $1}' | tr -cd '[0-9]'`
DATE=`date "+%Y-%m-%d"`

echo -e "$DATE\t$REV"
