
=head1 NAME

spamc - client for spamd

=head1 SYNOPSIS

  spamc [-d host] [-p port] [-h]

  -h		Print this help message and terminate without action
  -d host	Connect to spamd server on given host
  -p port	Connect to spamd server listening on given port

=head1 DESCRIPTION

Spamc is the client half of the spamc/spamd pair.  It should be used in place
of 'spamassassin -P' in scripts to process mail.  It will read the mail from
stdin, and spool it to its connection to spamd, then read the result back and
print it to stdout.  Spamc has extremely low overhead in loading, so it should
be much faster to load than the whole spamassassin program (and a perl VM).

See the README file in the C<spamd> directory of the SpamAssassin distribution
for more details.

=head1 SEE ALSO

C<spamd>
C<spamassassin>
C<Mail::SpamAssassin>

=head1 AUTHOR

Craig R Hughes E<lt>craig@hughes-family.orgE<gt>

=head1 PREREQUISITES

C<Mail::SpamAssassin>

=cut

