#!/bin/sh -e

# I hate debhelper, especially dh_link
# Fixing stuff I broke before (in 2.11-1 and 2.11-2)

if [ -h /etc/logcheck/ignore.d.paranoid ] ; then
	rm /etc/logcheck/ignore.d.paranoid
	mkdir /etc/logcheck/ignore.d.paranoid
fi

if [ -h /etc/logcheck/ignore.d.workstation ] ; then
	rm /etc/logcheck/ignore.d.workstation
	mkdir /etc/logcheck/ignore.d.workstation
fi

if [ -h /etc/logcheck/ignore.d.server/spamassassin ] ; then
	rm /etc/logcheck/ignore.d.server/spamassassin
fi

#DEBHELPER#
