#!/bin/sh

. ./config

for run in 1 2 3 4 5 6 7 8 9 10 
do
  mkdir tmp/10passrules > /dev/null 2>&1
  cp ../rules/[0-9]*.cf tmp/10passrules
  ./rewrite-cf-with-new-scores $SCORESET ../rules/50_scores.cf \
	tenpass_results/scores.$run > tmp/10passrules/50_scores.cf

  ./fp-fn-statistics --cffile=tmp/10passrules \
	--spam=tenpass_results/spam-test.log.$run \
	--ham=tenpass_results/ham-test.log.$run \
	-s $SCORESET > tmp/stats.$SCORESET.$run

done

echo === TCR statistics
for run in 1 2 3 4 5 6 7 8 9 10 
do
  grep TCR tmp/stats.$SCORESET.$run
done

