#!/bin/sh

cd $HOME/ftp/spamassassin/wordfreqs

# the new stuff is run on dogma and sonic now
dog=dogma.slashnull.org
rsync -vrze ssh $dog:ftp/spamassassin/wordfreqs/spam.dogma .
rsync -vrze ssh $dog:ftp/spamassassin/wordfreqs/nonspam.dogma .
son=spam.sonic.net
rsync -vrze ssh $son:ftp/spamassassin/wordfreqs/spam.sonic .
rsync -vrze ssh $son:ftp/spamassassin/wordfreqs/nonspam.sonic .

cat nonspam.local nonspam.sonic nonspam.dogma > nonspam.wf
cat spam.local spam.sonic spam.dogma > spam.wf

./settle-phrases > spamwords.freqs

echo "

cp spamwords.freqs ../rules/40_spam_phrases.cf

"

