#!/usr/bin/perl

use strict;
use Fcntl;

BEGIN { @AnyDBM_File::ISA = qw(DB_File GDBM_File NDBM_File SDBM_File); }
use AnyDBM_File;

use vars qw( %h $k $v @DBNAMES) ;

@DBNAMES = qw(count toks_ham toks_spam probs);

my $path = $ENV{HOME}."/.spamassassin/bayes";

foreach my $dbname (@DBNAMES) {
  my $name = $path.'_'.$dbname;
  my $db_var = 'db_'.$dbname;
  tie %{$h{$db_var}}, "AnyDBM_File",$name, O_RDONLY,0600
        or die "Cannot open file $name: $!\n";
}

my %seen = ();
my @k = ( keys(%{$h{db_toks_spam}}) , keys(%{$h{db_toks_ham}}) );
for my $key (@k) {
  next if (exists $seen{$key});
  $seen{$key} = 1;

  my $prob = $h{db_probs}->{$key};
  if (defined $prob) {
    $prob = unpack ('f', $prob);
  } else {
    $prob = 0.5;
  }

  my $sp = $h{db_toks_spam}->{$key}; $sp ||= 0;
  my $ns = $h{db_toks_ham}->{$key};  $ns ||= 0;
  printf ("%3.3f %8d %8d   %s\n", $prob, $sp, $ns, $key);
}

foreach my $dbname (@DBNAMES) {
  my $name = $path.'_'.$dbname;
  my $db_var = 'db_'.$dbname;
  untie %{$h{$db_var}};
}
