DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=
	sa-test.spamassassin.org; h=from:to:subject:message-id:date
	:mime-version:content-type; s=t0640; bh=15pFrAvOGi+eHKJgB6psh6iI
	BCbvYSuhPj+wQn6C7Ss=; b=WWBboo8qsl8/fCw5qKYTLnI94l1InwVD8gWqm5b2
	pnbdN+ze6YUQI0J7ngb37nllzXZgIbOiMaHxaax0YARt98qTFdJErzaaMOLkWy2E
	53s=
From: SpamAssassin Test <test@sa-test.spamassassin.org>
To: undisclosed-recipients:;
Subject: test message 18
Message-ID: <4A294538.10002@spamassassin.org>
Date: Mon, 08 Jun 2009 12:00:00 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii

testing
