DKIM-Signature: v=1; a=rsa-sha256; d=sa-test.spamassassin.org; h=from:to
	:subject:message-id:date:mime-version:content-type; s=t0768; bh=
	15pFrAvOGi+eHKJgB6psh6iIBCbvYSuhPj+wQn6C7Ss=; b=ZFopU9lJ/WFWddnO
	1nrYuptGphxfk2c4Tl0w/5HP0LhDMXX2KQRKHDh8p/AXxCERk6esOtX+BjME/ZOF
	PnFrSh7naSjaT22YrT91gLD548OK73YUxR3Zh5nVOmSfn0TM
From: SpamAssassin Test <test@sa-test.spamassassin.org>
To: undisclosed-recipients:;
Subject: test message 2
Message-ID: <4A294538.10002@spamassassin.org>
Date: Mon, 08 Jun 2009 12:00:00 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii

testing
