DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=
	sa-test.spamassassin.org; h=from:to:subject:message-id:date
	:mime-version:content-type; s=t0768; bh=15pFrAvOGi+eHKJgB6psh6iI
	BCbvYSuhPj+wQn6C7Ss=; b=1nTkj8819Yz/UW6F6rDKUERtV5QwdnFE46jDbvvj
	E7x2x5C8CIjhnBiy6ImT7YBT6W//erPosz5sKxu22PUj5/Zcd9e1tBLq5Q/lGDrX
	tdWepMsUxOUTFukn1GAmhFQx
From: SpamAssassin Test <test@sa-test.spamassassin.org>
To: undisclosed-recipients:;
Subject: test message 4
Message-ID: <4A294538.10002@spamassassin.org>
Date: Mon, 08 Jun 2009 12:00:00 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii

testing
