DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=
	sa-test.spamassassin.org; h=from:to:subject:message-id:date
	:mime-version:content-type; s=t1024d; bh=15pFrAvOGi+eHKJgB6psh6i
	IBCbvYSuhPj+wQn6C7Ss=; b=kveZJvWvWEUEJY1769i6WEEQcDm5pgS36dxcSYK
	CMbWzMt0YsfBJ6HZw8OL7L/wmMBlBkfCPGuA/thirxdXq2xYpFZaZ6nDvkNWezXS
	QCLi9RQlZB0OgkvkcnNIwS1X3n270QuumZYMjOGU7p9s4ABkeNbht5xguxCnoIBZ
	lyy0=
From: SpamAssassin Test <test@sa-test.spamassassin.org>
To: undisclosed-recipients:;
Subject: test message 12
Message-ID: <4A294538.10002@spamassassin.org>
Date: Mon, 08 Jun 2009 12:00:00 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii

testing
