DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=
	sa-test.spamassassin.org; h=from:to:subject:message-id:date
	:mime-version:content-type; s=t0768; t=1244419200; bh=15pFrAvOGi
	+eHKJgB6psh6iIBCbvYSuhPj+wQn6C7Ss=; b=NSUjTvM8mmW8D43clzf8wswBCr
	YSnBNsMhw6LEPGlZWXEUiSSgculoBK2V8L0hRTqMqpCzHpei8PesccAxrhSRPSBb
	CD9bqyd79GqAPxbgEGUlL0r9rpEV4ZVcUrIKHv
Content-Type: text/plain; charset=us-ascii
MIME-Version: 1.0
Date: Mon, 08 Jun 2009 12:00:00 +0000
Message-ID: <4A294538.10002@spamassassin.org>
Subject: test message 6
To: undisclosed-recipients:;
From: SpamAssassin Test <test@sa-test.spamassassin.org>

testing
