DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=
	sa-test.spamassassin.org; h=from:to:subject:message-id:date
	:mime-version:content-type; s=t0768; t=1244419200; bh=15pFrAvOGi
	+eHKJgB6psh6iIBCbvYSuhPj+wQn6C7Ss=; b=DgfhH71pMATYjqKko32MsRWxsO
	Js9XWb64+xVB8VzpypX3NaI7DyHTcTsEj+canFx8mLlk8ahNJb6XQHj+Lz9do4HB
	Jw4r9iuBvbxnJdbp9Tcw5Bey2zXYpKVmqQoMHr
Content-Type: text/plain; charset=us-ascii
MIME-Version: 1.0
Date: Mon, 08 Jun 2009 12:00:00 +0000
Message-ID: <4A294538.10002@spamassassin.org>
Subject: test message 5
To: undisclosed-recipients:;
From: SpamAssassin Test <test@sa-test.spamassassin.org>

testing
