#!/bin/sh

# 50 * * * * /home/jm/ftp/spamassassin/build/gen_freqs_from_nightly_mc

outdir=/home/jm/spamassassin.taint.org/qa/freqs

cd /home/jm/ftp/spamassassin/masses

(
echo "STARTING AT"; date

# you need to create this file with RSYNC_USERNAME and RSYNC_PASSWORD
# settings for your account in it.

. nightly_mc_passwords
export RSYNC_PASSWORD

mkdir all-results >/dev/null 2>&1
rsync -vrz $RSYNC_USERNAME@belphegore.hughes-family.org::corpus/. all-results

# now grep out the ones built today, and put copies into "uptodate"
today=`date +"%b %e"`   # "Oct 17"
yday=`date +"%b %e" --date='yesterday'`   # "Oct 16"

rm -rf uptodate; mkdir uptodate >/dev/null 2>&1
rm -rf timestamps; mkdir timestamps >/dev/null 2>&1
for f in all-results/*.log ; do
  if grep "mass-check results from" $f | egrep "$today|$yday" > dates ; then
    cp $f uptodate
    sort dates | tail -1 > timestamps/`basename $f`
  fi
done

cat uptodate/nonspam-*.log > nonspam.log
cat uptodate/spam-*.log > spam.log
make clean ; make freqs

echo "
Last update: `date`
Nonspam results used: `echo uptodate/nonspam*`
Spam results used: `echo uptodate/spam*`

`cat freqs`

Timestamps from mass-check output used:

`egrep . timestamps/*`
" > $outdir/DETAILS

cp freqs $outdir

echo $outdir
ls -l $outdir

echo "FINISHED AT"; date

) > nightly.log 2>&1

